{{- if eq .Values.cronJobType "daemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
    {{- include "geoipupdate.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "geoipupdate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "geoipupdate.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "geoipupdate.serviceAccountName" . }}
      restartPolicy: {{ .Values.restartPolicy }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if and (not .Values.createConfig.enabled) (not .Values.extraVolumes) }}
        []
      {{- else }}
      {{-   if .Values.createConfig.enabled }}
        - name: config
          emptyDir: {}
      {{-   end }}
      {{-   if .Values.extraVolumes }}
      {{-     with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{-     end }}
      {{-   end }}
      {{- end }}
      initContainers:
      {{- if and (not .Values.createConfig.enabled) (not .Values.extraInitContainers) }}
        []
      {{- else }}
      {{-   if .Values.createConfig.enabled }}
        - name: create-config
          image: "{{ .Values.createConfig.image.repository }}:{{ .Values.createConfig.image.tag }}"
          imagePullPolicy: {{ .Values.createConfig.image.pullPolicy }}
          {{- with .Values.createConfig.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.createConfig.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.createConfig.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: config
            mountPath: /config
      {{-   end }}
      {{-   if .Values.extraInitContainers }}
      {{-     with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
      {{-     end }}
      {{-   end }}
      {{- end }}
      containers:
        - name: geoipupdate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "geoipupdate.fullname" . }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if and (not .Values.createConfig.enabled) (not .Values.extraVolumeMounts) }}
            []
          {{- else }}
          {{-   if .Values.createConfig.enabled }}
            - name: config
              mountPath: /etc/GeoIP.conf
              subPath: GeoIP.conf
          {{-   end }}
          {{-   if .Values.extraVolumeMounts }}
          {{-     with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{-     end }}
          {{-   end }}
          {{- end }}
{{- end }}
