{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
    {{- include "geoipupdate.labels" . | nindent 4 }}
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - {{ include "geoipupdate.fullname" . }}
{{- end }}
