apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geoipupdate.fullname" . }}
  labels:
    {{- include "geoipupdate.labels" . | nindent 4 }}
  {{- with .Values.configSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  GEOIPUPDATE_ACCOUNT_ID: {{ .Values.configSecret.geoipupdateAccountID | b64enc }}
  GEOIPUPDATE_LICENSE_KEY: {{ .Values.configSecret.geoipupdateLicenseKey | b64enc }}
  GEOIPUPDATE_EDITION_IDS: {{ .Values.configSecret.geoipupdateEditionIDs | b64enc }}
  {{- if eq .Values.cronJobType "daemonSet" }}
  GEOIPUPDATE_FREQUENCY: {{ .Values.configSecret.geoipupdateFrequency | b64enc }}
  {{- else }}
  GEOIPUPDATE_FREQUENCY: {{ "0" | b64enc }}
  {{- end }}
  {{- if .Values.configSecret.geoipupdateHost }}
  GEOIPUPDATE_HOST: {{ .Values.configSecret.geoipupdateHost | b64enc }}
  {{- end }}
  {{- if .Values.configSecret.geoipupdateProxy }}
  GEOIPUPDATE_PROXY: {{ .Values.configSecret.geoipupdateProxy | b64enc }}
  {{- end }}
  {{- if .Values.configSecret.geoipupdateProxyUserPassword }}
  GEOIPUPDATE_PROXY_USER_PASSWORD: {{ .Values.configSecret.geoipupdateProxyUserPassword | b64enc }}
  {{- end }}
  {{- if .Values.configSecret.geoipupdateVerbose }}
  GEOIPUPDATE_VERBOSE: {{ .Values.configSecret.geoipupdateVerbose | b64enc }}
  {{- end }}
type: Opaque
